gsap.from('.section-two',{ scrollTrigger :'.section-two',opacity : 0, duration : 1.5, y : 100,  delay : 0.5 })
gsap.from('.section-three',{ scrollTrigger :'.section-three',opacity : 0, duration : 1.5, x : 100, delay : 0.5 })
gsap.from('.section-four',{ scrollTrigger :'.section-four',opacity : 0, duration : 1.5, y : 100, delay : 0.5 })
gsap.from('.section-five',{ scrollTrigger :'.section-five',opacity : 0, duration : 1.5, x : 100, delay : 0.5 })
gsap.from('.section-six',{ scrollTrigger :'.section-six',opacity : 0, duration : 1.5, y : -10, delay : 0.5 })
gsap.from('.section-seven',{ scrollTrigger :'.section-seven',opacity : 0, duration : 1.5, x : -100, delay : 0.5 })